from tkinter import *
root = Tk()
root.geometry("800x500")
root.title("Степан Калачев")
label = Label(root, text="Мат. расчеты Калачева", font=("Arial", 18))
label.pack(padx=20, pady=20)
textbox = Text(root, height=3, font=("Arial", 16))
textbox.pack(padx=20, pady=20)
buttonFrame = Frame(root)
buttonFrame.columnconfigure(0, weight=1)
buttonFrame.columnconfigure(1, weight=1)
buttonFrame.columnconfigure(2, weight=1)
buttonFrame.columnconfigure(3, weight=1)

btn1 = Button(buttonFrame, text="1", font=("Arial", 18))
btn2 = Button(buttonFrame, text="2", font=("Arial", 18))
btn3 = Button(buttonFrame, text="3", font=("Arial", 18))
btn4 = Button(buttonFrame, text="-", font=("Arial", 18))
btn5 = Button(buttonFrame, text="4", font=("Arial", 18))
btn6 = Button(buttonFrame, text="5", font=("Arial", 18))
btn7 = Button(buttonFrame, text="6", font=("Arial", 18))
btn8 = Button(buttonFrame, text="+", font=("Arial", 18))
btn9 = Button(buttonFrame, text="7", font=("Arial", 18))
btn10 = Button(buttonFrame, text="8", font=("Arial", 18))
btn11 = Button(buttonFrame, text="9", font=("Arial", 18))
btn12 = Button(buttonFrame, text="*", font=("Arial", 18))
btn13 = Button(buttonFrame, text="Clear", font=("Arial", 18))
btn14 = Button(buttonFrame, text="0", font=("Arial", 18))
btn15 = Button(buttonFrame, text="=", font=("Arial", 18))
btn16 = Button(buttonFrame, text="/", font=("Arial", 18))

btn1.grid(row=0, column=0, sticky="we")
btn2.grid(row=0, column=1, sticky="we")
btn3.grid(row=0, column=2, sticky="we")
btn4.grid(row=0, column=3, sticky="we")
btn5.grid(row=1, column=0, sticky="we")
btn6.grid(row=1, column=1, sticky="we")
btn7.grid(row=1, column=2, sticky="we")
btn8.grid(row=1, column=3, sticky="we")
btn9.grid(row=2, column=0, sticky="we")
btn10.grid(row=2, column=1, sticky="we")
btn11.grid(row=2, column=2, sticky="we")
btn12.grid(row=2, column=3, sticky="we")
btn13.grid(row=3, column=0, sticky="we")
btn14.grid(row=3, column=1, sticky="we")
btn15.grid(row=3, column=2, sticky="we")
btn16.grid(row=3, column=3, sticky="we")
buttonFrame.pack(fill="x")
root.mainloop()